// placeholder data for a list of guest before we fetch from an api
export const guests = [
  {
    id: 1,
    name: "Beyonce",
    email: "e9T6K@example.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 2,
    name: "Khalid",
    email: "khalid@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 3,
    name: "Lil Wayne",
    email: "lilwayne@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 4,
    name: "Kanye West",
    email: "kanye@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 5,
    name: "Drake",
    email: "drake@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 6,
    name: "Eminem",
    email: "eminem@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 7,
    name: "Kendrick Lamar",
    email: "kendrick@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
  {
    id: 8,
    name: "Nicki Minaj",
    email: "nicki@me.com",
    phone: "1234-567-890 x1234",
    job: "Singer",
    bio: "lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, voluptatum.",
  },
];
